Main: Lr7Proga.cpp Organization.cpp Worker.cpp Date.cpp
	g++ -o Lr7Proga Lr7Proga.cpp Organization.cpp Worker.cpp Date.cpp
Test: Organization.cpp Worker.cpp Date.cpp Test.cpp
	g++ -o Test -Dmain=_main Test.cpp Organization.cpp Worker.cpp Date.cpp -lm
