name: Lr7Proga

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd 7
        make Test
        ./Test
        gcov Organization.cpp Worker.cpp Date.cpp Test.cpp -r
        bash <(curl -s https://codecov.io/bash)

